---
# Add your data here:
PV_EMAIL : ""               # e-mail address you used to register at M-TEC portal
PV_PASSWORD : ""            # password you used to register at M-TEC portal

##########################
# Base config - probably no need to change
PV_BASE_URL : "https://energybutler.mtec-portal.com/api/sys/"  # Base URL of API
PV_TIMEOUT : 3         # Timeout (seconds) for querying the API
PV_MAX_LOGIN_RETRY : 3 # No. of retries for login

PV_DEMO_ACCOUNT : "2312942037@qq.com"    # e-mail adress of Demo account
PV_DEMO_STATION_ID : "1587705243920052226"

